version: '3.8'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: testdb
    command: --default-authentication-plugin=mysql_native_password

  setup_db:
    build: .
    depends_on:
      - db
    command: python get_raw_data.py
  
  api:
    build: .
    depends_on:
      - setup_db
    ports:
      - "5000:5000"
    command: python financial/api.py

